# Generated by Django 5.0.1 on 2024-05-23 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('quartier', models.CharField(max_length=12)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1)),
                ('age', models.CharField(max_length=10)),
                ('adresse', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('enregistré_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
            },
        ),
        migrations.CreateModel(
            name='facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=500)),
                ('payer', models.BooleanField(default=False)),
                ('dernière_modification', models.DateTimeField(auto_now_add=True)),
                ('type_facture', models.CharField(choices=[('R', 'Réçue'), ('P', 'Proformat'), ('F', 'Facture')], max_length=10)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('Administrateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facture.client')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
            },
        ),
        migrations.CreateModel(
            name='articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=32)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=100000)),
                ('quantité', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=100000)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facture.facture')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
